export type AddMapCarry = [
  [
    [0, false],
    [1, false],
    [2, false],
    [3, false],
    [4, false],
    [5, false],
    [6, false],
    [7, false],
    [8, false],
    [9, false]
  ],
  [
    [1, false],
    [2, false],
    [3, false],
    [4, false],
    [5, false],
    [6, false],
    [7, false],
    [8, false],
    [9, false],
    [0, true]
  ],
  [
    [2, false],
    [3, false],
    [4, false],
    [5, false],
    [6, false],
    [7, false],
    [8, false],
    [9, false],
    [0, true],
    [1, true]
  ],
  [
    [3, false],
    [4, false],
    [5, false],
    [6, false],
    [7, false],
    [8, false],
    [9, false],
    [0, true],
    [1, true],
    [2, true]
  ],
  [
    [4, false],
    [5, false],
    [6, false],
    [7, false],
    [8, false],
    [9, false],
    [0, true],
    [1, true],
    [2, true],
    [3, true]
  ],
  [
    [5, false],
    [6, false],
    [7, false],
    [8, false],
    [9, false],
    [0, true],
    [1, true],
    [2, true],
    [3, true],
    [4, true]
  ],
  [
    [6, false],
    [7, false],
    [8, false],
    [9, false],
    [0, true],
    [1, true],
    [2, true],
    [3, true],
    [4, true],
    [5, true]
  ],
  [
    [7, false],
    [8, false],
    [9, false],
    [0, true],
    [1, true],
    [2, true],
    [3, true],
    [4, true],
    [5, true],
    [6, true]
  ],
  [
    [8, false],
    [9, false],
    [0, true],
    [1, true],
    [2, true],
    [3, true],
    [4, true],
    [5, true],
    [6, true],
    [7, true]
  ],
  [
    [9, false],
    [0, true],
    [1, true],
    [2, true],
    [3, true],
    [4, true],
    [5, true],
    [6, true],
    [7, true],
    [8, true]
  ]
]
export type SubMapCarry = [
  [
    [0, false],
    [9, true],
    [8, true],
    [7, true],
    [6, true],
    [5, true],
    [4, true],
    [3, true],
    [2, true],
    [1, true]
  ],
  [
    [1, false],
    [0, false],
    [9, true],
    [8, true],
    [7, true],
    [6, true],
    [5, true],
    [4, true],
    [3, true],
    [2, true]
  ],
  [
    [2, false],
    [1, false],
    [0, false],
    [9, true],
    [8, true],
    [7, true],
    [6, true],
    [5, true],
    [4, true],
    [3, true]
  ],
  [
    [3, false],
    [2, false],
    [1, false],
    [0, false],
    [9, true],
    [8, true],
    [7, true],
    [6, true],
    [5, true],
    [4, true]
  ],
  [
    [4, false],
    [3, false],
    [2, false],
    [1, false],
    [0, false],
    [9, true],
    [8, true],
    [7, true],
    [6, true],
    [5, true]
  ],
  [
    [5, false],
    [4, false],
    [3, false],
    [2, false],
    [1, false],
    [0, false],
    [9, true],
    [8, true],
    [7, true],
    [6, true]
  ],
  [
    [6, false],
    [5, false],
    [4, false],
    [3, false],
    [2, false],
    [1, false],
    [0, false],
    [9, true],
    [8, true],
    [7, true]
  ],
  [
    [7, false],
    [6, false],
    [5, false],
    [4, false],
    [3, false],
    [2, false],
    [1, false],
    [0, false],
    [9, true],
    [8, true]
  ],
  [
    [8, false],
    [7, false],
    [6, false],
    [5, false],
    [4, false],
    [3, false],
    [2, false],
    [1, false],
    [0, false],
    [9, true]
  ],
  [
    [9, false],
    [8, false],
    [7, false],
    [6, false],
    [5, false],
    [4, false],
    [3, false],
    [2, false],
    [1, false],
    [0, false]
  ]
]
export type CmpMap = [
  [0, -1, -1, -1, -1, -1, -1, -1, -1, -1],
  [1, 0, -1, -1, -1, -1, -1, -1, -1, -1],
  [1, 1, 0, -1, -1, -1, -1, -1, -1, -1],
  [1, 1, 1, 0, -1, -1, -1, -1, -1, -1],
  [1, 1, 1, 1, 0, -1, -1, -1, -1, -1],
  [1, 1, 1, 1, 1, 0, -1, -1, -1, -1],
  [1, 1, 1, 1, 1, 1, 0, -1, -1, -1],
  [1, 1, 1, 1, 1, 1, 1, 0, -1, -1],
  [1, 1, 1, 1, 1, 1, 1, 1, 0, -1],
  [1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
]
