This is makeindex, version 2.17 [TeX Live 2023] (kpathsea + Thai support).
Scanning style file ./ctufit-thesis.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file ctufit-thesis.acn....done (54 entries accepted, 0 rejected).
Sorting entries....done (389 comparisons).
Generating output file ctufit-thesis.acr....done (51 lines written, 0 warnings).
Output written in ctufit-thesis.acr.
Transcript written in ctufit-thesis.alg.
